### ISSUE TITLE
Don't suspend user.

### ISSUE THREAD

**Issue by outline4** [olivierbon/craft-concierge#12]
Hi, 

On my site I've set `'autoLoginAfterAccountActivation' => true`. Because once the've registered I let them fill out their Address etc. 

Concierge automatically suspends the User. 

Would you mind adding a setting that prevents suspending new registrations? 

Or could you please please make a plugin that JUST send's an email to one or more email addresses once a new registration took place... Man, this is such basic stuff it really should be core... 

I hope you don't mind me being a little frustrated ;) 

Cheers  
Stefan

**Comment by olivierbon** [comment]
Hey Stefan, suspending the user is the point of Concierge I'm afraid.

> could you please please make a plugin that JUST send's an email to one or more email addresses once a new registration took place

You could Fork the plugin and [remove this line](https://github.com/olivierbon/craft-concierge/blob/master/src/Concierge.php#L162) so it stops suspending OR feel free to create a plugin base on concierge but without the functionality you don't need.

Alternatively, I think that [Sprout Form](https://plugins.craftcms.com/sprout-forms) offers what you need out of the box, for free.

**Comment by outline4** [comment]
Thanks for getting back. 

In fact, after tinkering a bit, I've adopted your workflow.  
Suspended users are spotted much more easily than anything else. 

Thank for this plugin, and keep it simple! (don't listen to me :)

Cheers 
Stefan

Btw: I think it's [Sprout Email](https://plugins.craftcms.com/sprout-email) that will trigger emails for all sorts of events. 

P.s. I love double negations: «without the functionality you don't need»
