### ISSUE TITLE
Concierge emails not being received and new users not appearing on concierge list

### ISSUE THREAD

**Issue by senpuukyakuu** [olivierbon/craft-concierge#18]
Hi, 
I've been using concierge for a couple of months, and until recently I realized that we're not receiving the emails nor seeing the users on the menu.
What information do you need me to send to further clarify?
I'm running Craft CMS 3.5.15.1 and I'm not really sure which version of concierge, since I can't see it.
Also, I'm receiving neither the system emails(the activation one) nor concierge's .
Although, If I resend the activation email from the cp, it delivers correctly.
Thanks, 
D

**Comment by olivierbon** [comment]
@senpuukyakuu I'm not able to replicate this. Things seem to work as expected.

You can see the version you are on under Settings → Plugins then look again Concierge for the version number.

Are you sure email sending is enabled (Settings → Concierge) and you have the messages defined properly (Utilities → System Messages)?

**Comment by senpuukyakuu** [comment]
Hi Oli, 
The version is 2.1.0 and it's now sending the emails, although is taking 15mins or so.
Is Concierge using the system default to send emails (in this case it'll be SendGrid).
And, even though I'm receiving the emails, the plugin is not behaving as expected, I still don't see any of the new users under the concierge list and it's not suspending them for some reason.
I can send you a video where you can see it.
Let me know what info do you need to do proper troubleshooting.

**Comment by olivierbon** [comment]
Hey Dan,

Concierge [sends email via Craft](https://github.com/olivierbon/craft-concierge/blob/master/src/services/ConciergeMailer.php#L48-L54), yes.

The process is [pretty straight forward](https://github.com/olivierbon/craft-concierge/blob/master/src/services/ConciergeMailer.php#L48-L54), if it's a new user, it gets suspended.

Anything particular about your site? Is it the site I know about with some duplicated users?

Are you able to test on a different environment without SendGrid to see if that makes a difference?

**Comment by senpuukyakuu** [comment]
Oli,
Now, that I'm checking.
I realized Concierge is not suspending the users.
We're using a custom plugin to plush the user into SalesForce, might it be
that is interfering with Concierge.

Event::on(User::class, User::EVENT_AFTER_SAVE, function(Event $e) {
   //  @var User $user
    $user = $e->sender;

    $currentScenario = $user->getScenario();
    if( $currentScenario != User::SCENARIO_PASSWORD){
         Plugin::$app->api->saveUser($user);
    }


});

The Custom plugin was already installed when we first installed the plugin
on June 24th and it was working fine until a month or so ag
 Is there any change in the Craft updates that might be affecting this?


Is there any log I can provide that can help you?
Thanks,
D,

**Comment by olivierbon** [comment]
I can't think of anything on the top of my head. Are you able to xDebug this and see what could be conflicting?

Have you tried using the native Settings → Users → Settings → Suspend users by default? Does that work?

**Comment by senpuukyakuu** [comment]
Hi Oli,
I've suspended the user by default and it's not suspending the users.
Regarding xDebug, what is exactly what you mean?
Thanks,
D,

**Comment by olivierbon** [comment]
If even suspending natively doesn't work then I'm not too sure.

What I mean by debugging is step in your code and see what could be the problem. If you disable your module, do things work?

**Comment by senpuukyakuu** [comment]
Hi Oli,
Sorry for the delayed response.
I've already figured it out, it was our custom Craft->SF interfering with
the suspendUser() method on an AFTER_SAVE call.
Seems to be working ok now.
Thanks a ton.
D,

**Comment by olivierbon** [comment]
@senpuukyakuu Glad you're sorted and thank you for letting me know!
