### ISSUE TITLE
Craft 4? Or is this plugin dead?

### ISSUE THREAD

**Issue by angieherrera** [olivierbon/craft-concierge#19]
Haven't seen a release since late 2019, so I'm wondering if this plugin is still in active development? If so, will there be a Craft 4 compatible version?

**Comment by olivierbon** [comment]
Hey @angieherrera, I will release an update soon.

Thank you!

**Comment by olivierbon** [comment]
Hey @angieherrera, mind [sharing your thoughts on this discussion](https://github.com/olivierbon/craft-concierge/discussions/20), please? Thank you!
