### ISSUE TITLE
New user accounts not set to 'Suspended'

### ISSUE THREAD

**Issue by j-greig** [olivierbon/craft-concierge#8]
I'm running Craft 3.1.33 and new users are not being suspended by Concierge, instead they are set to active straight away.

"Verify email addresses?" in User Settings is unchecked.

If I manually suspend the new account, then unsuspend it, the notification email does go out correctly.

Have I missed something? (It was working on my local install before upgrading to the latest version of Craft, not sure if this is part of the problem)

**Comment by olivierbon** [comment]
Hey, I'm not able to reproduce that.

Are you testing front end registrations and you are logout your Control Panel?
